### ISSUE TITLE
ZMusicUIFrame

### ISSUE THREAD

**Issue by chenjhg** [lyxia/zmusic#1]
zmusic-master/ZMusicUIFrame/ZMusicUIFrameTests/ZMusicUIFrameTests.swift:10:18: Cannot load underlying module for 'ZMusicUIFrame', 
framework not found Pods_ZMusicUIFrame请大神指点下，thank you!

**Comment by lyxia** [comment]
pod没清理干净，已修复，在更新下代码

**Comment by chenjhg** [comment]
zmusic-master/ZMusicUIFrame/ZMusicUIFrame/CuzNavigationContentController.swift:50:13: Value of type 'CuzNavigationBar' has no member 'snp'
zmusic-master/ZMusicUIFrame/ZMusicUIFrame/CuzNavigationBar.swift:45:19: Value of type 'UIImageView' has no member 'snp'
zmusic-master/ZMusicUIFrame/ZMusicUIFrame/UIView+Extension.swift:46:13: Value of type 'UIImageView' has no member 'snp'
请大神指点下，thank you!

**Comment by lyxia** [comment]
我重新拉了一次没有问题啊(⊙﹏⊙)b  你有没有把以前拉的删了再拉？
